Throw lança uma exceção manualmente.